spring:
  config:
    activate:
      on-profile: "prod"

build:
  version: "1.0"

loans:
  message: "Welcome to EazyBank loans related PROD APIs"
  contactDetails:
    name: "Swapnil Mishra - Product Owner"
    email: "swapnil@gmail.com"
  onCallSupport:
    - 9999999997
    - 9999999996